JetBrains/jetpad-projectional

- hybrid/src/main/java/jetbrains/jetpad/hybrid/HybridSynchronizer.java
- hybrid/src/main/java/jetbrains/jetpad/hybrid/TokenCompletion.java
Restoring naming consistency after commit 119a9cc.
> Rename `.positionSpec()` to `.editorSpec()

- projectional/src/main/java/jetbrains/jetpad/projectional/cell/ProjectionalPropertySynchronizer.java
- projectional/src/main/java/jetbrains/jetpad/projectional/cell/ProjectionalSynchronizers.java
My guess is that it is there for some historical reasons as I can’t see any use of it.
> forSingleRole sync: lift SourceT bound

- hybrid/src/main/java/jetbrains/jetpad/hybrid/TokenCellTraits.java
- hybrid/src/main/java/jetbrains/jetpad/hybrid/TokenOperations.java
- hybrid/src/test/java/jetbrains/jetpad/hybrid/HybridEditorTest.java
I believe this is better from the UX point of view.
Before this change if a user left an empty token (which is pretty hard to notice) and moved on editing the expression the parser would keep reparsing the expression successfully as if the token was still there. This is not only a potential source of confusion, but also causes de-synchronization of the model and its visual representation.
Now having an empty token makes the whole hybrid field become red and the model won’t be updated (if the parser stumbles on `ErrorToken`s as reasonable parsers do) until the empty token is removed or replaced with something else.
> hybrid: Replace empty tokens with errors

- grammar/src/main/java/jetbrains/jetpad/grammar/GrammarSugar.java
- grammar/src/main/java/jetbrains/jetpad/grammar/PersistentList.java
- grammar/src/test/java/jetbrains/jetpad/grammar/GrammarSugarTest.java
Like `separated` but allows for the trailing separator (think Python tuples).
This is [`sepEndBy`](https://hackage.haskell.org/package/parsec-3.1.7/docs/Text-Parsec-Combinator.html#v:sepEndBy) from parsec.
> grammar: New combinators

- projectional/src/main/java/jetbrains/jetpad/projectional/cell/BaseProjectionalSynchronizer.java
Fisrt, I found natural to add such an assert after investigating code in BaseProjectionalSynchronizer. Second, if target cell isn't empty, placeholder logic is broken: synchonizer will remove some targets child cell instead of placeholder.
> add assertion that target cell is empty in BaseProjectionalSynchonizer

- grammar/src/main/java/jetbrains/jetpad/grammar/GrammarSugar.java
emptyStart parameter in terminated() for the case where you don't start with "item" - (separator item)* [separator]
> emptyStart parameter in terminated()

- cell/src/main/java/jetbrains/jetpad/cell/text/TextEditingTrait.java
- cell/src/test/java/jetbrains/jetpad/cell/text/TextEditingTest.java
It's fired in other cases (backspace, ctrl-delete) but not in this one (select all and then backspace or delete). As a result we have different behavior in a hybrid editor for these cases.
> BECAME_EMPTY is not fired for clearSelection()

- cell/src/main/java/jetbrains/jetpad/cell/message/MessageController.java
- cell/src/main/java/jetbrains/jetpad/cell/message/MessageTrait.java
As appropriate CellContainerPeer is provided to CellContainer only after the CellContainer mapper is attached, MessageTrait could get NullEventDispatchThread instance.
> provide actual edt to MessageTrait

- cell/src/main/resources/jetbrains/jetpad/cell/toDom/style.css
I'm reverting this because there was code that relied on having font-size not being 0. Either way, I have a better fix coming in next.
> revert c6fee99 : don't set specific font-size for any domCell element.

- hybrid/src/test/java/jetbrains/jetpad/hybrid/HybridEditorTest.java
- hybrid/src/test/java/jetbrains/jetpad/hybrid/HybridEditorWithTransformedListTest.java
- hybrid/src/test/java/jetbrains/jetpad/hybrid/testapp/TestAppMain.java
- hybrid/src/test/java/jetbrains/jetpad/hybrid/testapp/mapper/ExprContainerMapper.java
- hybrid/src/test/java/jetbrains/jetpad/hybrid/testapp/mapper/ExprListMapper.java
- hybrid/src/test/java/jetbrains/jetpad/hybrid/testapp/mapper/ExprMapperFactory.java
- hybrid/src/test/java/jetbrains/jetpad/hybrid/testapp/model/EmptyExpr.java
- hybrid/src/test/java/jetbrains/jetpad/hybrid/testapp/model/ExprList.java
Compared to previous request:
* `ExprMapperFactory` visibility level lowered to package-private.
About `ExprListMapper`: this is a root mapper used outside the package, just like existing `ExprContainerMaper`. They both have to be `public`.
> DP-697 New tests: hybrid synchronizers write to list items transformed to properties

- hybrid/src/main/java/jetbrains/jetpad/hybrid/HybridSynchronizer.java
- hybrid/src/main/java/jetbrains/jetpad/hybrid/TokenListEditor.java
- hybrid/src/main/java/jetbrains/jetpad/hybrid/parser/BaseToken.java
- hybrid/src/main/java/jetbrains/jetpad/hybrid/parser/Token.java
Before only ValueToken had copy(). This allows us to simplify code a little in a couple of places. And it will be easier for clients to copy a list of tokens.
> token.copy()

- domUtil/src/main/java/jetbrains/jetpad/projectional/domUtil/DomTextEditor.java
Needed to properly draw additional cursors.
Increased value to 10 to avoid further changes if we would add more decoration types.
> new z-ordering for text editor layout

- cell/src/main/resources/jetbrains/jetpad/cell/toDom/style.css
Checked census-analyzer and workflow. Actually didn't notice any differences in the presentation.
> removed "width: fit-content" for ".vertical > div" and ".domCell"

- hybrid/src/main/java/jetbrains/jetpad/hybrid/TokenOperations.java
- hybrid/src/test/java/jetbrains/jetpad/hybrid/HybridEditorTest.java
- hybrid/src/test/java/jetbrains/jetpad/hybrid/testapp/mapper/ExprHybridEditorSpec.java
In case after reprinting some tokens change, if one of those changed
tokens was focused, we want to focus its replacement.
> Focus tokens after reprinting on split

- cell/src/main/java/jetbrains/jetpad/cell/position/CellDefaultPositionHandler.java
- cell/src/main/java/jetbrains/jetpad/cell/position/DefaultPositionHandler.java
- cell/src/main/java/jetbrains/jetpad/cell/position/PositionHandler.java
- cell/src/test/java/jetbrains/jetpad/cell/util/CellsTest.java
- projectional/src/main/java/jetbrains/jetpad/projectional/cell/BaseProjectionalSynchronizer.java
- projectional/src/test/java/jetbrains/jetpad/projectional/cell/ProjectionalListSynchronizerTest.java
It allows us to determine more easily (or automatically in some cases) that the compound cell is empty. 
Added test cases for both commits (failed before, passes after).
Ran "mvn clean install" for all four repositories (mapper, projectional, ot-model, datapad).
> calculating isHome() and isEnd() using children of a cell

- view/src/main/java/jetbrains/jetpad/projectional/view/toAwt/ImageUtil.java
- view/src/main/java/jetbrains/jetpad/projectional/view/toAwt/ViewContainerComponent.java
Currently we generate 220 dpi x2 image (let's say 1200x800 px). In the webapp we show it x1 (600x400 px). In awt now we have to show it x2 and it's quite big. 
getScaledImage code is from here:
http://stackoverflow.com/questions/12475503/how-to-change-the-size-of-an-image
> scaled image (to show x2 image as x1 in awt like in webapp)

- hybrid/src/main/java/jetbrains/jetpad/hybrid/parser/ValueToken.java
Needed for copy/paste from/to Hybrid editor implementation. Hybrid editors wishing to support text copying must add text generator to ValueTokens they create.
> Added text generation support to ValueToken

- completion/src/main/java/jetbrains/jetpad/completion/ByBoundsCompletionItem.java
- hybrid/src/test/java/jetbrains/jetpad/hybrid/TokenizerTest.java
- hybrid/src/test/java/jetbrains/jetpad/hybrid/testapp/mapper/ExprHybridEditorSpec.java
To match, input must start with the prefix and optionally may end with the suffix but must not exceed it. E.g., for strings, `"` will complete to empty string, `"a` and `"a"` will complete to `"a"`, but `"a"b` or `"a""` will not complete.
* This eliminates the need in having two completions (Simple, ByBounds) in Hybrid Specs for strings. ByBounds can do all the work.
* In non-eager-completion cells completion is still possible because there is only one matching item.
* When you paste a string without a closing quote, latter is autocompleted.
> ByBoundsCompletionItem can complete incomplete input

- projectional/src/main/java/jetbrains/jetpad/projectional/cell/ProjectionalObservableListSynchronizer.java
- projectional/src/test/java/jetbrains/jetpad/projectional/cell/ProjectionalListSynchronizerTest.java
addEmptyAfter test - I discovered that the certain part of code (jetbrains.jetpad.projectional.cell.ProjectionalObservableListSynchronizer.ItemHandler#addEmptyAfter) was not covered by tests. So I added this test. It is the only test that will fail if replace that method body with Runnables.EMPTY.
checking canCreateItem() - the hardest part was to write the test (fail before, pass after).
> checking canCreateItem() (newItem IllegalStateException fix)

- demo/src/main/java/jetbrains/jetpad/projectional/demo/hybridExpr/mapper/ExprHybridEditorSpec.java
- demo/src/main/java/jetbrains/jetpad/projectional/demo/indentDemo/hybrid/LambdaHybridEditorSpec.java
- hybrid/src/main/java/jetbrains/jetpad/hybrid/BaseHybridEditorSpec.java
- hybrid/src/main/java/jetbrains/jetpad/hybrid/SimpleHybridEditorSpec.java
- hybrid/src/main/java/jetbrains/jetpad/hybrid/SimpleHybridSynchronizer.java
- hybrid/src/main/java/jetbrains/jetpad/hybrid/TokenListEditor.java
- hybrid/src/main/java/jetbrains/jetpad/hybrid/parser/ParsingContextFactory.java
- hybrid/src/main/java/jetbrains/jetpad/hybrid/parser/SimpleParsingContext.java
- hybrid/src/main/java/jetbrains/jetpad/hybrid/parser/SimpleParsingContextFactory.java
- hybrid/src/main/java/jetbrains/jetpad/hybrid/util/SimpleHybridProperty.java
- hybrid/src/test/java/jetbrains/jetpad/hybrid/testapp/mapper/ExprHybridEditorSpec.java
- hybrid/src/test/java/jetbrains/jetpad/hybrid/util/SimpleHybridPropertyTest.java
There are pull requests in 3 different repositories (jetpad-projectional, jetpad-ot, datapad). They all have name: "ability to specify a parsingContext implementation". The main one is jetpad-projectional. The other two are updates of usages so that the compilation doesn't fail.
We need this to provide a different implementation of ParsingContext. For  example, to filter out comment tokens.
> ability to specify a parsingContext implementation

- hybrid/src/main/java/jetbrains/jetpad/hybrid/parser/SimpleParsingContext.java
So that we could reuse this default implementation. 
I could use this implementation instead of PyParsingContext which is the exact copy of SimpleParsingContext. I did the comment filtering in PyParsingContextFactory.
> SimpleParsingContext is public

- demo/src/main/java/jetbrains/jetpad/projectional/demo/hybridExpr/mapper/ExprHybridEditorSpec.java
- demo/src/main/java/jetbrains/jetpad/projectional/demo/indentDemo/hybrid/LambdaHybridEditorSpec.java
- hybrid/src/main/java/jetbrains/jetpad/hybrid/CompletionContext.java
- hybrid/src/main/java/jetbrains/jetpad/hybrid/SimpleHybridSynchronizer.java
- hybrid/src/main/java/jetbrains/jetpad/hybrid/TokenCompleter.java
- hybrid/src/main/java/jetbrains/jetpad/hybrid/TokenCompletion.java
- hybrid/src/main/java/jetbrains/jetpad/hybrid/Tokenizer.java
- hybrid/src/main/java/jetbrains/jetpad/hybrid/UnsupportedCompletionContext.java
- hybrid/src/main/java/jetbrains/jetpad/hybrid/util/HybridWrapperRole.java
- hybrid/src/test/java/jetbrains/jetpad/hybrid/BaseHybridEditorEditingTest.java
- hybrid/src/test/java/jetbrains/jetpad/hybrid/TokensUtil.java
- hybrid/src/test/java/jetbrains/jetpad/hybrid/testapp/mapper/CommentMapper.java
- hybrid/src/test/java/jetbrains/jetpad/hybrid/testapp/mapper/ExprHybridEditorSpec.java
- hybrid/src/test/java/jetbrains/jetpad/hybrid/testapp/mapper/ExprMapperFactory.java
- hybrid/src/test/java/jetbrains/jetpad/hybrid/testapp/model/Comment.java
We need access to the token list in token completion for comment completion so that we can get the text for the tokens after the comment and then delete those tokens. 
See BaseHybridEditorEditingTest.commentInTheMiddle()
Interface changes:
* new completionContext parameter in tokenCompletion.getTokenCompletion()
* new removeToken(index) method in CompletionContext
Because of the change in tokenCompletion.getTokenCompletion(), the implementing classes has to be updated. As a result we have changed in jetpad-ot (funlang, lambda, modelUtil, workflow) and datapad.
There are three pull requests ("access to token list in token completion").
I'm passing 4 instances of CompletionContext.UNSUPPORTED. It looks like we don't need them in all 4 cases. If we come across such cases, we'll have to think …
> access to token list in token completion

- grammar/src/main/java/jetbrains/jetpad/grammar/RuleContext.java
- grammar/src/main/java/jetbrains/jetpad/grammar/parser/LRParser.java
- grammar/src/test/java/jetbrains/jetpad/grammar/BaseParserGenerationTest.java
- grammar/src/test/java/jetbrains/jetpad/grammar/GrammarSugarTest.java
- grammar/src/test/java/jetbrains/jetpad/grammar/GrammarTestUtil.java
Changes against https://github.com/JetBrains/jetpad-projectional/pull/158
* `getLexemeValues()` instead of `getLexemesValues()`
NB Kate please merge no sooner than on Monday
> RuleContext can return matched lexemes values

- hybrid/src/main/java/jetbrains/jetpad/hybrid/CompletionTokenizer.java
- hybrid/src/main/java/jetbrains/jetpad/hybrid/TokenOperations.java
- hybrid/src/test/java/jetbrains/jetpad/hybrid/CompletionTokenizerTest.java
Against https://github.com/JetBrains/jetpad-projectional/pull/162: `CompletionTokenizer` instead of `CompletionBasedTokenizer`.
> Completion tokenizer is now public API

- hybrid/src/main/java/jetbrains/jetpad/hybrid/BaseHybridSynchronizer.java
- hybrid/src/main/java/jetbrains/jetpad/hybrid/HybridSynchronizer.java
- hybrid/src/main/java/jetbrains/jetpad/hybrid/HybridWrapperRoleCompletion.java
- hybrid/src/main/java/jetbrains/jetpad/hybrid/SimpleHybridProperty.java
- hybrid/src/main/java/jetbrains/jetpad/hybrid/SimpleHybridSynchronizer.java
- hybrid/src/test/java/jetbrains/jetpad/hybrid/BaseHybridEditorEditingTest.java
- hybrid/src/test/java/jetbrains/jetpad/hybrid/SimpleHybridPropertyTest.java
- hybrid/src/test/java/jetbrains/jetpad/hybrid/testapp/model/SimpleExprContainer.java
I'd also like to remove BaseHybridSynchronizer from public API via replacing it with HybridSynchronizer interface, but not now.
There are corresponding pull requests to ot and datapad:
https://github.com/JetBrains/jetpad-ot/pull/50
https://github.com/JetBrains/datapad/pull/6
> remove TokenListEditor from public API; get rid of hybrid.util package

- hybrid/src/main/java/jetbrains/jetpad/hybrid/BaseHybridSynchronizer.java
- hybrid/src/main/java/jetbrains/jetpad/hybrid/parser/TokenUtil.java
Changes since https://github.com/JetBrains/jetpad-projectional/pull/166
* Renamed `join()` to `getText()`, like in `jetbrains.jetpad.hybrid.TokenCompleter`
* Renamed local variable `joined` to `text`
* Added license text to the file header
> Exracted getting text of tokens list to public util

- hybrid/src/main/java/jetbrains/jetpad/hybrid/BaseHybridSynchronizer.java
Related to (but does not depend on) https://github.com/JetBrains/jetpad-projectional/pull/185
This is a prerequisite to implement clipboard content interchanges between projectional and hybrid editors. The client code is expected to use this constant when adjusting projectional synchronizer.
> Changed TOKENS_CONTENT constant visibility to public

- cell/src/main/java/jetbrains/jetpad/cell/CellContainer.java
- cell/src/main/java/jetbrains/jetpad/cell/text/TextEditingTrait.java
- cell/src/main/java/jetbrains/jetpad/cell/toView/CellContainerToViewMapper.java
- cell/src/test/java/jetbrains/jetpad/cell/text/TextEditingTest.java
- event/src/main/java/jetbrains/jetpad/event/ContentKinds.java
- event/src/main/java/jetbrains/jetpad/event/MultilineTextClipboardContent.java
- event/src/main/java/jetbrains/jetpad/event/SingleLineTextClipboardContent.java
- event/src/main/java/jetbrains/jetpad/event/TextContentHelper.java
- event/src/main/java/jetbrains/jetpad/event/dom/ClipboardSupport.java
- projectional/src/main/java/jetbrains/jetpad/projectional/cell/BaseProjectionalSynchronizer.java
- projectional/src/main/java/jetbrains/jetpad/projectional/cell/ProjectionalRoleSynchronizer.java
- projectional/src/test/java/jetbrains/jetpad/projectional/cell/ProjectionalListSynchronizerTest.java
- view/src/main/java/jetbrains/jetpad/projectional/view/toAwt/ViewContainerComponent.java
- view/src/main/java/jetbrains/jetpad/projectional/view/toGwt/ViewContainerToElementMapper.java
NB: there is dependent pull request https://github.com/JetBrains/datapad/pull/11 which must be merged immediately after this. If you like both, please make sure I'm online and ready, then accept both.
Changes since https://github.com/JetBrains/jetpad-projectional/pull/185
* All naming and messaging recommendations accepted
* Introduced new content kind: `MULTILINE_TEXT`. There is also `ANY_TEXT` content kind for controllers convenience (see usages).
* In `BaseProjectionalSynchronizer`: from-content and to-content concepts are separated because in fact they don't depend on each other. Editor can support pasting from several content kinds and not support generating text, why not. Also, coupling text-generation with some clipboard content kind seems unnecessary. Consequently, …
> Projectional synchronizer can support ClipboardContents of different kinds

- event/src/main/java/jetbrains/jetpad/event/TextContentHelper.java
`LF` -> `NEWLINE`
`CR` -> `CARRIAGE_RETURN`
Use `NEWLINE` in `joinLines()` method.
> In TextContentHelper: better constants names; used constants where applicable

- hybrid/src/test/java/jetbrains/jetpad/hybrid/BaseHybridEditorEditingTest.java
- projectional/src/main/java/jetbrains/jetpad/projectional/cell/SelectionSupport.java
When you have multiple no-space-to-left tokens, more than one may be selected upon shift + left arrow, and in this case middle was is inserted to the incorrect place. Fixed.
> DP-819 Fixed right-to-left tokens selection

- projectional/src/main/java/jetbrains/jetpad/projectional/cell/BaseProjectionalSynchronizer.java
- projectional/src/test/java/jetbrains/jetpad/projectional/cell/ProjectionalListSynchronizerTest.java
Changes since https://github.com/JetBrains/jetpad-projectional/pull/196:
* Removed `insertNonNull...` methods, inlined nullchecks
> BaseProjectionalSynchronizer: added nullchecks on paste

- cell/src/main/java/jetbrains/jetpad/cell/CellContainer.java
- cell/src/main/java/jetbrains/jetpad/cell/toView/CellContainerToViewMapper.java
- event/src/main/java/jetbrains/jetpad/event/ContentKinds.java
- event/src/main/java/jetbrains/jetpad/event/MultilineTextClipboardContent.java
- event/src/main/java/jetbrains/jetpad/event/SingleLineTextClipboardContent.java
- event/src/main/java/jetbrains/jetpad/event/TextContentHelper.java
- event/src/main/java/jetbrains/jetpad/event/dom/ClipboardSupport.java
- view/src/main/java/jetbrains/jetpad/projectional/view/toAwt/ViewContainerComponent.java
As discussed in https://github.com/JetBrains/jetpad-projectional/pull/190, `ANY_TEXT` is not ok, so replaced with util methods pair: `isText()` and `getText()`.
> Dropped ANY_TEXT content kind; replaced usages with util-methods calls

- hybrid/src/main/java/jetbrains/jetpad/hybrid/ParsingHybridProperty.java
- hybrid/src/main/java/jetbrains/jetpad/hybrid/SimpleHybridProperty.java
- hybrid/src/test/java/jetbrains/jetpad/hybrid/BaseHybridEditorEditingTest.java
- hybrid/src/test/java/jetbrains/jetpad/hybrid/HybridEditorEditingTest.java
- hybrid/src/test/java/jetbrains/jetpad/hybrid/ParsingHybridPropertyTest.java
- hybrid/src/test/java/jetbrains/jetpad/hybrid/testapp/model/SimpleExprContainer.java
The tokenFocusAfterReparseAndSplitGivesDifferentTokens test fails when I try to apply it to a simple hybrid editor, still investigating the cause.
> DP-989 pretty printing support for SimpleHybridEditor

- projectional/src/main/java/jetbrains/jetpad/projectional/cell/BaseProjectionalSynchronizer.java
- projectional/src/test/java/jetbrains/jetpad/projectional/cell/ProjectionalListSynchronizerTest.java
You may setup projectional synchronizer to yield only textual clipboard without full cut/copy/paste support. This works similar to copying some text from disabled UI element: you can select and copy, but can't cut and paste.
> Projectional sync: allowed copying only text

- cell/src/test/java/jetbrains/jetpad/cell/EditingTestCase.java
- hybrid/src/main/java/jetbrains/jetpad/hybrid/BaseHybridSynchronizer.java
- hybrid/src/test/java/jetbrains/jetpad/hybrid/BaseHybridEditorEditingTest.java
- hybrid/src/test/java/jetbrains/jetpad/hybrid/TokensUtil.java
Just like Projectional Editor does, Hybrid now copies tokens after copy() and before paste(). First copy needed to protect clipboard content from edits in source tokens; second copy needed to separate multiple pastes of same content.
In `TokenUtils`: minor changes: removed unused, corrected expected/actual order.
> DP-1019 Hybrid: copy tokens after copy and before paste

- cell/src/main/java/jetbrains/jetpad/cell/completion/CompletionItems.java
- cell/src/test/java/jetbrains/jetpad/cell/text/ValidTextCompletionTest.java
- completion/src/main/java/jetbrains/jetpad/completion/BaseCompletionItem.java
- completion/src/main/java/jetbrains/jetpad/completion/CompletionItem.java
- completion/src/main/java/jetbrains/jetpad/completion/WrapperCompletionItem.java
- hybrid/src/main/java/jetbrains/jetpad/hybrid/HybridWrapperRoleCompletion.java
- hybrid/src/main/java/jetbrains/jetpad/hybrid/TokenCompletionItems.java
- hybrid/src/test/java/jetbrains/jetpad/hybrid/BaseHybridEditorEditingTest.java
- hybrid/src/test/java/jetbrains/jetpad/hybrid/CompletionTokenizerTest.java
- hybrid/src/test/java/jetbrains/jetpad/hybrid/TokensUtil.java
- hybrid/src/test/java/jetbrains/jetpad/hybrid/testapp/mapper/ExprHybridEditorSpec.java
The problem with `boolean` priority was in `HybridWrapperRoleCompletion`: it erased priority info in `WrapperCompletionItem` setting it to constant. This complicated, for example, implementing multiple String completion items of different priorities (flat priorities cause ambiguous completion). New implementation does not erase but decreases the priority instead.
NB: there is dependent request which must be merged immediately: https://github.com/JetBrains/datapad/pull/12
> CompletionItem: changed matching priority from boolean to integer

- cell/src/main/java/jetbrains/jetpad/cell/completion/Completion.java
- cell/src/main/java/jetbrains/jetpad/cell/completion/CompletionConfig.java
- cell/src/main/java/jetbrains/jetpad/cell/completion/DefaultCompletionConfig.java
- cell/src/main/java/jetbrains/jetpad/cell/text/TextEditingTrait.java
- cell/src/test/java/jetbrains/jetpad/cell/text/ValidTextCompletionTest.java
- hybrid/src/main/java/jetbrains/jetpad/hybrid/TokenCellTraits.java
- hybrid/src/test/java/jetbrains/jetpad/hybrid/testapp/mapper/ExprHybridEditorSpec.java
- hybrid/src/test/java/jetbrains/jetpad/hybrid/testapp/mapper/Tokens.java
- We don't need strictlyPrefixed.isEmpty() check in the hybrid editor but we need it in the projecitonal editor. 
- Added test: jetbrains.jetpad.cell.text.ValidTextCompletionTest#rightTransformOnEnd_strictlyPrefixedNotEmpty
- Didn't add a test in hybrid tests. Adding ELLIPSIS ("...") broke two tests. Implementing CompletionConfig in TokenCellTraits (jetbrains/jetpad/hybrid/TokenCellTraits.java:196) fixed those tests.
> DP-1026 No completion in the dot position

- completion/src/main/java/jetbrains/jetpad/completion/ByBoundsCompletionItem.java
- completion/src/test/java/jetbrains/jetpad/completion/BaseCompletionItemTestCase.java
- completion/src/test/java/jetbrains/jetpad/completion/ByBoundsWithSuffixTest.java
- completion/src/test/java/jetbrains/jetpad/completion/ByBoundsWithoutSuffixTest.java
- hybrid/src/test/java/jetbrains/jetpad/hybrid/BaseHybridEditorEditingTest.java
- hybrid/src/test/java/jetbrains/jetpad/hybrid/CompletionTokenizerTest.java
- hybrid/src/test/java/jetbrains/jetpad/hybrid/testapp/mapper/ExprHybridEditorSpec.java
**NB:** there's dependent pull request https://github.com/JetBrains/datapad/pull/13. Please merge both or neither.
The previous `ByBoundsCompletionItem` implementation could complete even if a string does not end with specified suffix. For quoted string case
* `"` -> `""`
* `"a` -> `"a"`
* `"b"` -> `"b"`
This was needed to satisfy both editor case (`"` completes to a string) and copypaste case (`"abc"`completes to `"abc"`). However, there is one issue about this implementation: when you have any valid token (id, number), typing a quote from its home position turns this token into a string. For example, you have integer `10`, and type from home position `"`.
* Expected: `"" 10`
* Actual: `"10"`
Correct solution: having different completions for editor case (simple `"`-matching) and …
> ByBoundsCompletionItem: if suffix specified, it is required

- hybrid/src/main/java/jetbrains/jetpad/hybrid/ParsingHybridProperty.java
- hybrid/src/test/java/jetbrains/jetpad/hybrid/testapp/model/SimpleExprContainer.java
The comments are broken by this commit: bee76d7 DP-989 pretty printing support for SimpleHybridEditor by @azlobinjb. 
The tests were passing because we had SimpleParsingContextFactory instead of CommentParsingContextFactory in this place.
The tests should be fixed either in this pull request (or somewhere else).
> broken comments 

- hybrid/src/main/java/jetbrains/jetpad/hybrid/HybridEditorSpecUtil.java
- hybrid/src/test/java/jetbrains/jetpad/hybrid/testapp/model/SimpleExprContainer.java
In this case the parsing context factory should be a derivative of a hybridEditorSpec.
> better way of creating parsing context factory

- projectional/src/main/java/jetbrains/jetpad/projectional/cell/BaseProjectionalSynchronizer.java
- projectional/src/main/java/jetbrains/jetpad/projectional/cell/ProjectionalRoleSynchronizer.java
- projectional/src/test/java/jetbrains/jetpad/projectional/cell/ProjectionalListSynchronizerTest.java
Changes since https://github.com/JetBrains/jetpad-projectional/pull/227
* Removed runnable parameter from `disablePlaceholder()`
* Added checks which throw exceptions on incorrect combination
* Added tests expecting those exceptions
> ProjSync: client can disable a placeholder so that empty model produces no output

- cell/src/main/java/jetbrains/jetpad/cell/Cell.java
- cell/src/main/java/jetbrains/jetpad/cell/CellContainer.java
- cell/src/main/java/jetbrains/jetpad/cell/toDom/BaseCellMapper.java
- cell/src/main/java/jetbrains/jetpad/cell/toDom/CellToDomCss.java
- cell/src/main/java/jetbrains/jetpad/cell/toView/BaseCellMapper.java
- cell/src/main/resources/jetbrains/jetpad/cell/toDom/style.css
This fixes http://jetpad.myjetbrains.com/youtrack/issue/DP-1065. And, this commit brings accurate background handling for 'link' cells. No more background clearance for focused cell which is also a link.
> DP-1065: cell style when hovered and un-hovered

- cell/src/main/java/jetbrains/jetpad/cell/trait/CompositeCellTrait.java
- hybrid/src/main/java/jetbrains/jetpad/hybrid/BaseHybridSynchronizer.java
- hybrid/src/main/java/jetbrains/jetpad/hybrid/TextTokenCell.java
- hybrid/src/main/java/jetbrains/jetpad/hybrid/TokenTextEditPostProcessorTrait.java
- hybrid/src/main/java/jetbrains/jetpad/hybrid/TokensEditPostProcessor.java
- hybrid/src/test/java/jetbrains/jetpad/hybrid/BaseHybridEditorEditingTest.java
Changes since https://github.com/JetBrains/jetpad-projectional/pull/241: all commits squashed.
Unfortunately I could not extract a fix to `CompositeCellTrait` because a) the feature does not work without a fix and b) the problem with this trait is not visible without a new feature. Writing a test covering only a fix is not that easy: another copypaste is a source of alike errors; using `Thread` or dynamic proxy to find out a caller fails to compile in IDEA because by default it uses inspections for whole GWT module even in tests; disabling this needs configuration which will be annoying for the team.
So the cleanest way is having a fix together with a feature — its tests cover the fix just fine.
> Implemented tokens edit postprocessor

- cell/src/main/java/jetbrains/jetpad/cell/toDom/BaseCellMapper.java
- cell/src/main/java/jetbrains/jetpad/cell/toDom/CellToDomCss.java
- cell/src/main/resources/jetbrains/jetpad/cell/toDom/style.css
Dotted outline is applied when the non-leaf (non-token) cell is focused but not selected. These are actions or any other cell that supports focus and does not support selection.
> DP-1081 Separated selected and focused (outlined) styles

- cell/src/main/java/jetbrains/jetpad/cell/text/CellTextEditor.java
- cell/src/main/java/jetbrains/jetpad/cell/text/TextEditingTrait.java
- cell/src/main/java/jetbrains/jetpad/cell/text/TextEditor.java
- hybrid/src/main/java/jetbrains/jetpad/hybrid/TokenCellTraits.java
- hybrid/src/test/java/jetbrains/jetpad/hybrid/BaseHybridEditorEditingTest.java
Changes in `TextEditingTrait` caused by possible processed token removal (resulting in cell detach). Earlier current token also had a chance to be removed, but this was happening in other paths which took this into a consideration and no error was encountered.
Changes in `TextEditingTrait` are covered by new and some old tests.
> DP-1136 Fixed uncommenting a comment with a nested comment

- cell/src/main/java/jetbrains/jetpad/cell/indent/IndentCell.java
- cell/src/main/java/jetbrains/jetpad/cell/indent/IndentUtil.java
- cell/src/main/java/jetbrains/jetpad/cell/toDom/IndentRootCellMapper.java
- cell/src/main/java/jetbrains/jetpad/cell/toView/IndentRootCellMapper.java
- cell/src/main/java/jetbrains/jetpad/cell/util/CellFactory.java
Currently we can have only 2 spaces for each indent level.
In Python the standard is 4 spaces.
> ability to set indentNumSpaces

- projectional/src/main/java/jetbrains/jetpad/projectional/cell/ProjectionalObservableListSynchronizer.java
- projectional/src/main/java/jetbrains/jetpad/projectional/cell/ProjectionalSynchronizers.java
- projectional/src/main/java/jetbrains/jetpad/projectional/generic/CollectionEditor.java
- projectional/src/test/java/jetbrains/jetpad/projectional/cell/ProjectionalListSynchronizerTest.java
It will allow having more empty lines at the end of the cell on Enter so that it's easier to enter, for example, two functions with two empty lines between them (in accordance with the python standard).
> allow more empty lines at the end

- projectional/src/main/java/jetbrains/jetpad/projectional/selection/SelectionSupport.java
- projectional/src/test/java/jetbrains/jetpad/projectional/selection/SelectionControllerLegacyTest.java
This happened on multiple items delete in projectional syncronizer. Please see comment in `SelectionSupport` for details.
Because we can't change `ArrayList` implementation, we have to allow `mySelectionController` being inconsistent for some time.
If you run a test without a fix, it will fail, but you will see another exception. That's because some `finally` block throws another one which suppresses original.
> Fixed OutOfBounds exception on items remove

- cell/src/main/java/jetbrains/jetpad/cell/completion/CompletionSupport.java
- cell/src/main/java/jetbrains/jetpad/cell/text/TextEditingTrait.java
- cell/src/main/java/jetbrains/jetpad/cell/util/Cells.java
- hybrid/src/main/java/jetbrains/jetpad/hybrid/BaseHybridSynchronizer.java
- hybrid/src/main/java/jetbrains/jetpad/hybrid/HybridWrapperRoleCompletion.java
- hybrid/src/main/java/jetbrains/jetpad/hybrid/TokenTextEditPostProcessorTrait.java
- hybrid/src/main/java/jetbrains/jetpad/hybrid/TokensEditPostProcessor.java
- hybrid/src/test/java/jetbrains/jetpad/hybrid/BaseHybridEditorEditingTest.java
- projectional/src/main/java/jetbrains/jetpad/projectional/cell/BaseProjectionalSynchronizer.java
- projectional/src/test/java/jetbrains/jetpad/projectional/cell/ProjectionalListSynchronizerTest.java
Synchronous with https://github.com/JetBrains/datapad/pull/28, please merge both or neither.
This request contains prerequisites for dependent (main) one. It contains of the following changesets:
* `BaseProjectionalSynchronizer` and `ProjectionalListSynchronizerTest`: enable eager completion in projectional editor;
* `HybridWrapperRoleCompletion`: take into consideration that setting tokens may cause model detach;
* The rest: handle force (Ctrl+Space) completion — single automatic item (`TextEditingTrait`) or from menu (`CompletionSupport`).
> Completion and tokens postprocessing improvements

- hybrid/src/main/java/jetbrains/jetpad/hybrid/BaseHybridSynchronizer.java
- hybrid/src/test/java/jetbrains/jetpad/hybrid/BaseHybridEditorEditingTest.java
It's needed to provide context (current token index) in the token list.
> getCurrentCellIndex()

- projectional/src/main/java/jetbrains/jetpad/projectional/cell/BaseProjectionalSynchronizer.java
- projectional/src/main/java/jetbrains/jetpad/projectional/cell/ProjectionalRoleSynchronizer.java
- projectional/src/test/java/jetbrains/jetpad/projectional/cell/ProjectionalListSynchronizerTest.java
NB: this is synchronous with https://github.com/JetBrains/datapad/pull/32, please merge both or neither.
Always eager completion fails a test from jetpad-experimental which I missed. This request makes eager/non-eager completion a subject of configuration so that old (non-eager) behavior is the default.
> DP-1230 Configurable eager completion

- hybrid/src/main/java/jetbrains/jetpad/hybrid/TextTokenCell.java
- hybrid/src/test/java/jetbrains/jetpad/hybrid/BaseHybridEditorEditingTest.java
The problem in previous implementation was that `TokenCellTrait`, though being composite, overrode some methods so that token text editing postprocessor didn't get called. This implementation defines a composite trait of higher-level, so that postprocessor is guaranteed to be called.
> DP-1235 Fixed token cell text edit postprocessing
