JetBrains/jetpad-projectional

- cell/src/main/java/jetbrains/jetpad/cell/text/ValidTextEditingTrait.java
- cell/src/test/java/jetbrains/jetpad/cell/completion/CompletionTestCase.java
- cell/src/test/java/jetbrains/jetpad/cell/text/ValidTextCompletionTest.java
Spotted this one while digging into right side transforms
> Fix index out of range exception

- completion/src/main/java/jetbrains/jetpad/completion/SimpleCompletionItem.java
There are `@Nonnull` annotations there anyway.
> Remove unneeded null checks

- cell/src/main/java/jetbrains/jetpad/cell/Cell.java
- projectional/src/test/java/jetbrains/jetpad/projectional/cell/ProjectionalListSynchronizerTest.java
The bug was introduced in 598d2ec.
> Fix deletion in indent cells.

- cell/src/main/java/jetbrains/jetpad/cell/indent/IndentUtil.java
- cell/src/main/java/jetbrains/jetpad/cell/mappers/BasePopupManager.java
- cell/src/main/java/jetbrains/jetpad/cell/mappers/CellMapperContext.java
- cell/src/main/java/jetbrains/jetpad/cell/mappers/PopupManager.java
- cell/src/main/java/jetbrains/jetpad/cell/toDom/BaseCellMapper.java
- cell/src/main/java/jetbrains/jetpad/cell/toDom/CellContainerToDomMapper.java
- cell/src/main/java/jetbrains/jetpad/cell/toDom/CellToDomContext.java
- cell/src/main/java/jetbrains/jetpad/cell/toDom/DomPopupManager.java
- cell/src/main/java/jetbrains/jetpad/cell/toDom/IndentRootCellMapper.java
- cell/src/main/java/jetbrains/jetpad/cell/toUtil/AncestorUtil.java
- cell/src/main/java/jetbrains/jetpad/cell/toUtil/CounterSpec.java
- cell/src/main/java/jetbrains/jetpad/cell/toUtil/CounterUtil.java
- cell/src/main/java/jetbrains/jetpad/cell/toUtil/Counters.java
- cell/src/main/java/jetbrains/jetpad/cell/toUtil/HasCounters.java
- cell/src/main/java/jetbrains/jetpad/cell/toView/BaseCellMapper.java
- cell/src/main/java/jetbrains/jetpad/cell/toView/CellContainerToViewMapper.java
- cell/src/main/java/jetbrains/jetpad/cell/toView/CellToViewContext.java
- cell/src/main/java/jetbrains/jetpad/cell/toView/DefaultCellMapper.java
- cell/src/main/java/jetbrains/jetpad/cell/toView/ImageCellMapper.java
- cell/src/main/java/jetbrains/jetpad/cell/toView/IndentRootCellMapper.java
- cell/src/main/java/jetbrains/jetpad/cell/toView/ScrollCellMapper.java
- cell/src/main/java/jetbrains/jetpad/cell/toView/TextCellMapper.java
- cell/src/main/java/jetbrains/jetpad/cell/toView/VerticalCellMapper.java
- cell/src/test/java/jetbrains/jetpad/cell/completion/CompletionTestCase.java
- hybrid/src/test/java/jetbrains/jetpad/hybrid/HybridEditorTest.java
- view/src/test/java/jetbrains/jetpad/projectional/view/ViewTest.java
1) What do you think of CellMapper interface?
2) Should packages 'toUtil' and 'mappers' be merged?
> Cell mappers refactoring

- cell/src/main/java/jetbrains/jetpad/cell/completion/BaseCompletionController.java
- cell/src/main/java/jetbrains/jetpad/cell/completion/CompletionSupport.java
- cell/src/main/java/jetbrains/jetpad/cell/text/TextEditingTrait.java
- cell/src/test/java/jetbrains/jetpad/cell/completion/CompletionHandlerTestCase.java
- cell/src/test/java/jetbrains/jetpad/cell/completion/NonTextCellCompletionTest.java
- cell/src/test/java/jetbrains/jetpad/cell/error/ErrorPopupTextCompletionTest.java
- cell/src/test/java/jetbrains/jetpad/cell/text/ValidTextCompletionTest.java
fix completion reopen after focus loss bugs: ISE for non-text cell, no action for text cell
> fix completion reopen after focus loss bugs

- grammar/src/main/java/jetbrains/jetpad/grammar/GrammarSugar.java
terminator parameter in GrammarSugar.terminated() for the case where the terminator is different from the separator
> terminator parameter in GrammarSugar.terminated()

- hybrid/src/main/java/jetbrains/jetpad/hybrid/TokenCompletion.java
- hybrid/src/test/java/jetbrains/jetpad/hybrid/HybridEditorTest.java
New drop-down selection is appended, but it should replace the old one (DP-610).
> New drop-down selection is appended, but it should replace the old one

- hybrid/src/main/java/jetbrains/jetpad/hybrid/util/HybridWrapperRole.java
- hybrid/src/test/java/jetbrains/jetpad/hybrid/HybridEditorTest.java
We need a way to hide tokens for HybridWrapperRole. Cannot use hybridSynchronizer.isHideTokensInMenus() because we create hybridSynchronizer only on completion.
> hideTokensInMenus for HybridWrapperRole

- cell/src/main/java/jetbrains/jetpad/cell/TextCell.java
- cell/src/main/java/jetbrains/jetpad/cell/toDom/TextCellMapper.java
- domUtil/src/main/java/jetbrains/jetpad/projectional/domUtil/DomTextEditor.java
this will allow me to control the size of currently empty place holder text cell in CellWithActions
> implementing setting font-size on a text-cell

- cell/src/main/java/jetbrains/jetpad/cell/TextCell.java
- cell/src/main/java/jetbrains/jetpad/cell/completion/CompletionSupport.java
- cell/src/main/java/jetbrains/jetpad/cell/position/PositionHandler.java
- cell/src/main/java/jetbrains/jetpad/cell/text/TextCellToEditorAdapter.java
- cell/src/main/java/jetbrains/jetpad/cell/text/TextEditing.java
- cell/src/main/java/jetbrains/jetpad/cell/text/TextEditingTrait.java
- cell/src/main/java/jetbrains/jetpad/cell/text/TextEditor.java
- cell/src/main/java/jetbrains/jetpad/cell/text/TextEditorCell.java
- cell/src/main/java/jetbrains/jetpad/cell/text/TextNavigationTrait.java
- cell/src/main/java/jetbrains/jetpad/cell/text/TextPositionHandler.java
- cell/src/main/java/jetbrains/jetpad/cell/text/ValidTextEditingTrait.java
Since last request I have removed coupling of TextCell and TextEditor. But I have left TextEditorCell to provide all necessary functionality to traits (TextNavigationTrait, TextNavigationTrait and CompletionSupport).
> introduce text editor

- cell/src/main/java/jetbrains/jetpad/cell/completion/CompletionSupport.java
- cell/src/main/java/jetbrains/jetpad/cell/text/CellTextEditor.java
- cell/src/main/java/jetbrains/jetpad/cell/text/TextEditing.java
- cell/src/main/java/jetbrains/jetpad/cell/text/TextEditingTrait.java
- cell/src/main/java/jetbrains/jetpad/cell/text/TextEditor.java
- cell/src/main/java/jetbrains/jetpad/cell/text/TextNavigationTrait.java
- cell/src/main/java/jetbrains/jetpad/cell/text/TextPositionHandler.java
- cell/src/main/java/jetbrains/jetpad/cell/text/ValidTextEditingTrait.java
- cell/src/test/java/jetbrains/jetpad/cell/completion/NonTextCellCompletionTest.java
make CellTextEditor package private; specify default value for CompletionSupport.EDITOR
> make CellTextEditor package private; default value for CompletionSupport.EDITOR

- hybrid/src/main/java/jetbrains/jetpad/hybrid/HybridSynchronizer.java
This fixes http://jetpad.myjetbrains.com/youtrack/issue/DP-737
Now we can make SeparatedCellList package private. I'd like it, but I'm not sure we should do this.
> fix HybridSynchronizer target separated list

- cell/src/main/java/jetbrains/jetpad/cell/completion/CompletionSupport.java
- cell/src/test/java/jetbrains/jetpad/cell/completion/CompletionHandlerTestCase.java
this fixes http://jetpad.myjetbrains.com/youtrack/issue/DP-836
> fix completion controller deactivate for not focusable cell

- cell/src/main/java/jetbrains/jetpad/cell/toDom/CellContainerToDomMapper.java
- cell/src/main/java/jetbrains/jetpad/cell/toDom/CellToDomCss.java
- cell/src/main/java/jetbrains/jetpad/cell/toDom/TextCellMapper.java
- cell/src/main/resources/jetbrains/jetpad/cell/toDom/style.css
this fixes http://jetpad.myjetbrains.com/youtrack/issue/DP-878
> set fit content width css to TextCell only

- cell/src/main/java/jetbrains/jetpad/cell/toDom/BaseCellMapper.java
- cell/src/main/java/jetbrains/jetpad/cell/toDom/IndentRootCellMapper.java
- cell/src/main/resources/jetbrains/jetpad/cell/toDom/style.css
As far as I've checked, FF works well.
> get flexbox back

- cell/src/main/java/jetbrains/jetpad/cell/message/MessageController.java
- cell/src/main/java/jetbrains/jetpad/cell/message/MessageTrait.java
- cell/src/main/java/jetbrains/jetpad/cell/toDom/BaseCellMapper.java
- cell/src/main/java/jetbrains/jetpad/cell/toView/BaseCellMapper.java
- cell/src/main/java/jetbrains/jetpad/cell/util/Cells.java
- cell/src/test/java/jetbrains/jetpad/cell/EditableCellContainer.java
- cell/src/test/java/jetbrains/jetpad/cell/EditingTestCase.java
- cell/src/test/java/jetbrains/jetpad/cell/message/MessageControllerTest.java
- cell/src/test/java/jetbrains/jetpad/cell/message/PopupsMappingTest.java
this commit fixes the bug: when cell is attached to cell container with preset message property, NPE is thrown on that message property change
> fix message controller setup

- cell/src/main/java/jetbrains/jetpad/cell/position/CellDefaultPositionHandler.java
- cell/src/main/java/jetbrains/jetpad/cell/position/DefaultPositionHandler.java
- cell/src/main/java/jetbrains/jetpad/cell/position/EmptyPositionHandler.java
- cell/src/main/java/jetbrains/jetpad/cell/position/PositionHandler.java
- cell/src/main/java/jetbrains/jetpad/cell/text/TextPositionHandler.java
- cell/src/main/java/jetbrains/jetpad/cell/util/Cells.java
- cell/src/test/java/jetbrains/jetpad/cell/util/CellsTest.java
Checked "mvn clean install" in the 4 repositories.
> positionHandler.isEmpty()

- view/src/main/java/jetbrains/jetpad/projectional/view/toAwt/ViewContainerComponent.java
I realized that there is a much simpler solution.
> scaling image

- hybrid/src/main/java/jetbrains/jetpad/hybrid/SimpleHybridSynchronizer.java
- hybrid/src/main/java/jetbrains/jetpad/hybrid/TokenCellTraits.java
- hybrid/src/test/java/jetbrains/jetpad/hybrid/BaseHybridEditorEditingTest.java
- hybrid/src/test/java/jetbrains/jetpad/hybrid/HybridEditorEditingTest.java
- hybrid/src/test/java/jetbrains/jetpad/hybrid/HybridEditorTest.java
- hybrid/src/test/java/jetbrains/jetpad/hybrid/SimpleHybridEditorEditingTest.java
- hybrid/src/test/java/jetbrains/jetpad/hybrid/testapp/mapper/SimpleExprContainerMapper.java
Also typo in the class name and simple editing tests
> ClassCast for SimpleHybridSynchronizer

- cell/src/main/java/jetbrains/jetpad/cell/Cell.java
- cell/src/main/java/jetbrains/jetpad/cell/text/TextEditing.java
- cell/src/main/java/jetbrains/jetpad/cell/text/TextEditingTrait.java
- cell/src/main/java/jetbrains/jetpad/cell/text/ValidTextEditingTrait.java
- cell/src/main/java/jetbrains/jetpad/cell/trait/CellTrait.java
- cell/src/main/java/jetbrains/jetpad/cell/trait/CompositeCellTrait.java
- cell/src/main/java/jetbrains/jetpad/cell/trait/DerivedCellTrait.java
- cell/src/test/java/jetbrains/jetpad/cell/EditableCellContainer.java
- cell/src/test/java/jetbrains/jetpad/cell/EditingTestCase.java
- completion/src/main/java/jetbrains/jetpad/completion/ByBoundsCompletionItem.java
- hybrid/src/main/java/jetbrains/jetpad/hybrid/BaseHybridSynchronizer.java
- hybrid/src/main/java/jetbrains/jetpad/hybrid/TextTokenCell.java
- hybrid/src/main/java/jetbrains/jetpad/hybrid/TokenOperations.java
- hybrid/src/main/java/jetbrains/jetpad/hybrid/Tokenizer.java
- hybrid/src/test/java/jetbrains/jetpad/hybrid/BaseHybridEditorEditingTest.java
- hybrid/src/test/java/jetbrains/jetpad/hybrid/HybridEditorCopyPasteTest.java
- hybrid/src/test/java/jetbrains/jetpad/hybrid/HybridEditorEditingTest.java
- hybrid/src/test/java/jetbrains/jetpad/hybrid/SimpleHybridEditorEditingTest.java
- hybrid/src/test/java/jetbrains/jetpad/hybrid/TokenizerTest.java
- hybrid/src/test/java/jetbrains/jetpad/hybrid/TokensUtil.java
- hybrid/src/test/java/jetbrains/jetpad/hybrid/testapp/mapper/ExprHybridEditorSpec.java
- hybrid/src/test/java/jetbrains/jetpad/hybrid/testapp/mapper/ExprMapperFactory.java
- hybrid/src/test/java/jetbrains/jetpad/hybrid/testapp/mapper/StringExprMapper.java
- hybrid/src/test/java/jetbrains/jetpad/hybrid/testapp/mapper/ValueExprCloner.java
- hybrid/src/test/java/jetbrains/jetpad/hybrid/testapp/mapper/ValueExprTextGen.java
- hybrid/src/test/java/jetbrains/jetpad/hybrid/testapp/model/StringExpr.java
- projectional/src/test/java/jetbrains/jetpad/projectional/cell/ProjectionalListSynchronizerTest.java
- projectional/src/test/java/jetbrains/jetpad/projectional/cell/ProjectionalPropertySynchronizerTest.java
Changes against https://github.com/JetBrains/jetpad-projectional/pull/137 are only in tests:
* Resolved merge conflicts
* In `BaseHybridEditorEditingTest` renamed `myTargetCell` to `targetCell` because it's not private
> Implemented a textual copypaste in hybrid editor

- hybrid/src/main/java/jetbrains/jetpad/hybrid/TokenListEditor.java
- hybrid/src/test/java/jetbrains/jetpad/hybrid/TokenListEditorTest.java
- hybrid/src/test/java/jetbrains/jetpad/hybrid/testapp/mapper/ExprHybridEditorSpec.java
- hybrid/src/test/java/jetbrains/jetpad/hybrid/testapp/mapper/ExprParsingContextFactory.java
- hybrid/src/test/java/jetbrains/jetpad/hybrid/testapp/mapper/ValueExprNodeCloner.java
- hybrid/src/test/java/jetbrains/jetpad/hybrid/testapp/model/Comment.java
when parsingContextFactory reduces the number of tokens.
Added a test (reparseWithComment) that failed before, passes after.
> fixed IllegalStateException

- hybrid/src/main/java/jetbrains/jetpad/hybrid/Completer.java
- hybrid/src/main/java/jetbrains/jetpad/hybrid/HybridWrapperRoleCompletion.java
- hybrid/src/main/java/jetbrains/jetpad/hybrid/TokenCompleter.java
- hybrid/src/main/java/jetbrains/jetpad/hybrid/UnsupportedCompleter.java
- hybrid/src/main/java/jetbrains/jetpad/hybrid/parser/TerminatorToken.java
- hybrid/src/test/java/jetbrains/jetpad/hybrid/BaseHybridEditorEditingTest.java
- hybrid/src/test/java/jetbrains/jetpad/hybrid/TokenListEditorTest.java
- hybrid/src/test/java/jetbrains/jetpad/hybrid/testapp/mapper/ExprHybridEditorSpec.java
1) added asserts for prefix and name in TerminatorToken constructor
2) out of bounds exception fix became irrelevant because of Alexey Z's changes
3) SimpleToken suggestions I'll do in a separate pull-request.
There is a dependent pull request in datapad:
JetBrains/datapad#7
> terminator token prefix

- hybrid/src/main/java/jetbrains/jetpad/hybrid/parser/IdentifierToken.java
- hybrid/src/main/java/jetbrains/jetpad/hybrid/parser/IntValueToken.java
- hybrid/src/main/java/jetbrains/jetpad/hybrid/parser/SimpleToken.java
1) renamed simpleToken.myName -> simpleToken.myText
2) simplified IdentifierToken, IntValueToken
3) added check for null simpleToken.myName
Later should remove "new SimpleToken()".
> myName -> myText, using simpleToken.myText

- cell/src/main/java/jetbrains/jetpad/cell/text/ValidTextEditingTrait.java
- cell/src/test/java/jetbrains/jetpad/cell/completion/CompletionTestCase.java
- cell/src/test/java/jetbrains/jetpad/cell/text/ValidTextCompletionTest.java
- completion/src/main/java/jetbrains/jetpad/completion/BaseCompletionParameters.java
- completion/src/main/java/jetbrains/jetpad/completion/CompletionParameters.java
- hybrid/src/main/java/jetbrains/jetpad/hybrid/HybridWrapperRoleCompletion.java
- hybrid/src/test/java/jetbrains/jetpad/hybrid/BaseHybridEditorEditingTest.java
Changes since https://github.com/JetBrains/jetpad-projectional/pull/179
* Resolved merge conflicts.
Please read comments in previous requests.
> Bulk completion on pasting to ValidTextEditingTrait

- cell/src/main/java/jetbrains/jetpad/cell/text/ValidTextEditingTrait.java
- cell/src/main/java/jetbrains/jetpad/cell/util/Cells.java
- hybrid/src/main/java/jetbrains/jetpad/hybrid/TextTokenCell.java
- hybrid/src/main/java/jetbrains/jetpad/hybrid/TokenCellTraits.java
- hybrid/src/main/java/jetbrains/jetpad/hybrid/TokenCompleter.java
- hybrid/src/main/java/jetbrains/jetpad/hybrid/TokenListEditor.java
- hybrid/src/main/java/jetbrains/jetpad/hybrid/TokenOperations.java
- hybrid/src/main/java/jetbrains/jetpad/hybrid/parser/BaseToken.java
- hybrid/src/main/java/jetbrains/jetpad/hybrid/parser/CommentToken.java
- hybrid/src/main/java/jetbrains/jetpad/hybrid/parser/ErrorToken.java
- hybrid/src/main/java/jetbrains/jetpad/hybrid/parser/Token.java
- hybrid/src/test/java/jetbrains/jetpad/hybrid/BaseHybridEditorEditingTest.java
- hybrid/src/test/java/jetbrains/jetpad/hybrid/TokenListEditorTest.java
- hybrid/src/test/java/jetbrains/jetpad/hybrid/TokensUtil.java
- hybrid/src/test/java/jetbrains/jetpad/hybrid/testapp/mapper/ExprHybridEditorSpec.java
Dependent pull requests:
JetBrains/datapad#10
> uncomment, fixed caret positions after processComments()

- projectional/src/main/java/jetbrains/jetpad/projectional/cell/SelectionSupport.java
- projectional/src/test/java/jetbrains/jetpad/projectional/cell/SelectionTest.java
Changes since https://github.com/JetBrains/jetpad-projectional/pull/204:
* Added license text
> DP-1010 In ProjectionalSync: fixed selection low priority recognition

- hybrid/src/main/java/jetbrains/jetpad/hybrid/SimpleHybridSynchronizer.java
- hybrid/src/test/java/jetbrains/jetpad/hybrid/BaseHybridEditorTest.java
fixes http://jetpad.myjetbrains.com/youtrack/issue/DP-1020
> DP-1020: proper validity state for comment

- projectional/src/main/java/jetbrains/jetpad/projectional/cell/SelectionSupport.java
- projectional/src/test/java/jetbrains/jetpad/projectional/cell/SelectionTest.java
Please read explanations in https://github.com/JetBrains/jetpad-projectional/pull/208
Changes compared to previous pull request: more accurate positioning (home/end).
> DP-1010 Selection change clears selections of lower levels

- projectional/src/main/java/jetbrains/jetpad/projectional/util/CellNavigationController.java
make static CellNavigationController.install() public, all other methods private, fix static ourWithBounds definition
> cleanup CellNavigationController API

- hybrid/src/main/java/jetbrains/jetpad/hybrid/ParsingHybridProperty.java
- hybrid/src/test/java/jetbrains/jetpad/hybrid/ParsingHybridPropertyTest.java
Related to #216. Fixes one additional case (missing comment on start/restart).
> fix missing comment on start

- cell/src/main/java/jetbrains/jetpad/cell/TraitPropagator.java
- cell/src/main/java/jetbrains/jetpad/cell/message/MessageController.java
- cell/src/test/java/jetbrains/jetpad/cell/TraitPropagatorTest.java
- cell/src/test/java/jetbrains/jetpad/cell/message/MessageControllerTest.java
- cell/src/test/java/jetbrains/jetpad/cell/message/MessageControllerTestCase.java
- cell/src/test/java/jetbrains/jetpad/cell/message/MessagePopupsDelayTest.java
extract common logic for cell controller propagating the same trait to all cell container's cells
> cell trait propagating controller

- hybrid/src/main/java/jetbrains/jetpad/hybrid/HybridEditorSpecUtil.java
I will use that method in datalore to replace the direct creation of CommentParsingContextFactory (jetbrains/datalore/model/hybrid/properties/PyHybridSpecs.java:85)
> create parsingContextFactory from commentSpec

- completion/src/main/java/jetbrains/jetpad/completion/CompletionSupplier.java
- hybrid/src/main/java/jetbrains/jetpad/hybrid/TokenCompletionSupplier.java
- hybrid/src/test/java/jetbrains/jetpad/hybrid/CompletionTokenizerTest.java
- hybrid/src/test/java/jetbrains/jetpad/hybrid/TokensUtil.java
- hybrid/src/test/java/jetbrains/jetpad/hybrid/testapp/mapper/ExprHybridEditorSpec.java
Plus one test. The test is not directly related but that functionality was not covered before.
> reuse for getting comment completion item

- cell/src/main/resources/jetbrains/jetpad/cell/toDom/style.css
a fix for http://jetpad.myjetbrains.com/youtrack/issue/DP-850
> default cursor for popups text

- cell/src/main/java/jetbrains/jetpad/cell/message/MessageTrait.java
- cell/src/main/java/jetbrains/jetpad/cell/message/StyleApplicator.java
This fixes http://jetpad.myjetbrains.com/youtrack/issue/DP-1085 and should lessen editor lags during complex editing caused by popups re-creation.
> update message popups and cell decorations when user stops editing

- hybrid/src/main/java/jetbrains/jetpad/hybrid/ParsingHybridProperty.java
- hybrid/src/test/java/jetbrains/jetpad/hybrid/SimpleHybridEditorExternalTokensChangeTest.java
- hybrid/src/test/java/jetbrains/jetpad/hybrid/testapp/model/SimpleExprContainer.java
Changes since https://github.com/JetBrains/jetpad-projectional/pull/238: added a license text.
> DP-1064 Accurate comment token handiling when editing

- cell/src/main/java/jetbrains/jetpad/cell/message/MessageTrait.java
- cell/src/test/java/jetbrains/jetpad/cell/message/MessagePopupsDelayTest.java
fixes http://jetpad.myjetbrains.com/youtrack/issue/DP-1111
> fix messages updates application after postpone

- cell/src/main/java/jetbrains/jetpad/cell/position/Positions.java
- projectional/src/main/java/jetbrains/jetpad/projectional/selection/SelectionController.java
- projectional/src/main/java/jetbrains/jetpad/projectional/selection/SelectionSupport.java
- projectional/src/test/java/jetbrains/jetpad/projectional/selection/SelectionControllerLegacyTest.java
One-commit version of https://github.com/JetBrains/jetpad-projectional/pull/249.
> Selection escalated if lower-level selection found

- projectional/src/main/java/jetbrains/jetpad/projectional/cell/ProjectionalObservableListSynchronizer.java
- projectional/src/main/java/jetbrains/jetpad/projectional/generic/CollectionEditor.java
- projectional/src/test/java/jetbrains/jetpad/projectional/cell/ProjectionalListSynchronizerTest.java
Improved one-commit version of https://github.com/JetBrains/jetpad-projectional/pull/256. **Warning:** there's synchronous request https://github.com/JetBrains/datapad/pull/24, please merge **both or neither**.
> List sync: create new on nonempty item remove

- cell/src/main/java/jetbrains/jetpad/cell/text/TextEditing.java
- cell/src/main/java/jetbrains/jetpad/cell/text/TextEditingTrait.java
- cell/src/test/java/jetbrains/jetpad/cell/EditableCellContainer.java
- cell/src/test/java/jetbrains/jetpad/cell/EditingTestCase.java
- event/src/main/java/jetbrains/jetpad/event/KeyStrokeSpecs.java
- projectional/src/main/java/jetbrains/jetpad/projectional/util/CellNavigationController.java
- projectional/src/test/java/jetbrains/jetpad/projectional/util/CellNavigationControllerTest.java
2nd part of http://jetpad.myjetbrains.com/youtrack/issue/DP-1153
Depends on https://github.com/JetBrains/jetpad-mapper/pull/81
> DP-1153: tab navigation

- cell/src/main/java/jetbrains/jetpad/cell/text/ValidTextEditingTrait.java
- event/src/main/java/jetbrains/jetpad/event/DerivedEvent.java
- event/src/main/java/jetbrains/jetpad/event/Event.gwt.xml
- event/src/main/java/jetbrains/jetpad/event/Events.java
- event/src/main/java/jetbrains/jetpad/event/PropertyChangeEventWrapper.java
- hybrid/src/main/java/jetbrains/jetpad/hybrid/TokenCellTraits.java
- hybrid/src/test/java/jetbrains/jetpad/hybrid/BaseHybridEditorEditingTest.java
One-commit version of https://github.com/JetBrains/jetpad-projectional/pull/254.
> DP-1184 Type before comment does not cause retokenizing

- cell/src/main/java/jetbrains/jetpad/cell/text/TextNavigationTrait.java
- cell/src/test/java/jetbrains/jetpad/cell/text/TextEditingTest.java
- event/src/main/java/jetbrains/jetpad/event/KeyStrokeSpecs.java
- projectional/src/test/java/jetbrains/jetpad/projectional/util/CellNavigationControllerTest.java
disable home/end in TextNavigationTrait, add tests, enable selection with Ctrl+Shift+Left
> DP-1153: text navigation shortcuts

- cell/src/main/java/jetbrains/jetpad/cell/completion/CompletionMenu.java
- cell/src/test/java/jetbrains/jetpad/cell/completion/CompletionHandlerTestCase.java
merged version of https://github.com/JetBrains/jetpad-projectional/pull/269
> DP-1203: fix 'white box instead of completion'

- projectional/src/main/java/jetbrains/jetpad/projectional/cell/ProjectionalObservableListSynchronizer.java
- projectional/src/main/java/jetbrains/jetpad/projectional/cell/ProjectionalPropertySynchronizer.java
- projectional/src/main/java/jetbrains/jetpad/projectional/cell/ProjectionalRoleSynchronizer.java
- projectional/src/main/java/jetbrains/jetpad/projectional/generic/CollectionEditor.java
- projectional/src/main/java/jetbrains/jetpad/projectional/generic/ItemsSplitterJoiner.java
- projectional/src/main/java/jetbrains/jetpad/projectional/generic/SplitJoinHandler.java
- projectional/src/test/java/jetbrains/jetpad/projectional/cell/ProjectionalListSynchronizerTest.java
NB: there is dependent pull request https://github.com/JetBrains/datapad/pull/35. I haven't tested this one separately from the other, so please merge both or neither.
For all explanations see dependent request.
> DP-1152 DP-1163 Projectional editor items split and join

- hybrid/pom.xml
- hybrid/src/main/java/jetbrains/jetpad/hybrid/TokenCompleter.java
- hybrid/src/main/java/jetbrains/jetpad/hybrid/TokenOperations.java
- hybrid/src/test/java/jetbrains/jetpad/hybrid/BaseHybridEditorEditingTest.java
This is a member of a triple pull request. Please merge all of them or neither.
Dependent pull requests to be merged synchronously:
~~https://github.com/JetBrains/jetpad-mapper/pull/83~~ https://github.com/JetBrains/jetpad-mapper/pull/84
https://github.com/JetBrains/datapad/pull/36
> DP-1232 Less events on tokens change
